spring.application.name=demo

spring.security.user.name=admin
spring.security.user.password={noop}secret123

#JWT Secret Key
security.jwt.secret-key=5367566859703373367639792F423F452848284D6251655468576D5A71347437
security.jwt.expiration-time=3600000

#H2 config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
